language: go

env:
    matrix:
        - MY_GOOS=darwin MY_GOARCH=386
        - MY_GOOS=darwin MY_GOARCH=amd64
        - MY_GOOS=linux MY_GOARCH=386
        - MY_GOOS=linux MY_GOARCH=amd64
        - MY_GOOS=windows MY_GOARCH=386
        - MY_GOOS=windows MY_GOARCH=amd64
    global:
      - secure: "Fu4wTgNFbNnfp9xv0WzV1Qp26McYTpN0/HuDQV2Zo6oUcezyXIVv3B7P59Xp/JDo9OSXDJ62cUXbDzDJ7voEc4cSi+z/DpL47yfsN+ixcHlvkvKVPC4kAhp4VfJveKb4bRefZeWflHaPPcM9Q1769Ubt3dlOgt8jEgS6O7ePE4A7KsxthPvWXwZF5PRJAiXELCzd8zb3+/OpN58CxmI1v9RdDQMbE4tOXZ0+QlYHaDndajfQzljmQpwlojwbKvTd7YfXA1nSK4wwY68DfUHlYG9y+CbmO5xBgpXb3bFpH5a3nNRS0lxzAtONfDL+BZ+cODmoUKxdd64mFm1fDyy6HasYIlZ5twCwWFjCu3CJtiroiGJzCslUlfht+s4K2yjmbwjrSWPSvvmOAsEWz3NCEUihdluvdfvPYwusYC3ZHwgCigNq85uZpZwd1MF2Lptuna5q1hEytxWjQxpQBXjPj1xeJ4GS1twwqKZYFzaOloZoEn+2b9Y81AFEfn5IjC5fjsC8KjTN2tp+ZdDtiqOEuJK2RHIl7PgW8kdrh5Yac9ZAOycpAN5gdSTD1Sr927b+q0EPUX0uGon/2FTO4BF1w7Lbfisht7gztiZ9bQrDEfmBcRQt1y0ig10OsxPQGQun42OHjqpO+tL3I6aBInh3rSsR7nEYrGPgAfJYP411rTM="

# workaround for travis-ci/gimme#25 to pick up latest version of gimme and run again
before_install:
    - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
    - chmod 600 ~/.netrc
    - export GOOS="${MY_GOOS}"
    - export GOARCH="${MY_GOARCH}"

script:
    - go install -v ./...

after_success:
    - cd $GOPATH/bin/
    - export CURRENT_ENV_DIR=${MY_GOOS}_${MY_GOARCH}
    - export PCKG_FILE=${CURRENT_ENV_DIR}.zip
    - mkdir -p $CURRENT_ENV_DIR
    - cp -f $GOPATH/bin/* $CURRENT_ENV_DIR/
    - zip -r $PCKG_FILE $CURRENT_ENV_DIR

deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: "${GOPATH}/bin/${MY_GOOS}_${MY_GOARCH}.zip"
    skip_cleanup: true
    on:
        tags: true

notifications:
    email: false
